aws_region         = "us-east-1"
project_name       = "agentic-devops"
environment        = "staging"
vpc_cidr           = "10.1.0.0/16"
availability_zones = ["us-east-1a", "us-east-1b"]
public_subnets     = ["10.1.1.0/24", "10.1.2.0/24"]
cluster_version    = "1.29"
node_instance_type = "t3.small"
node_desired       = 2
node_min           = 1
node_max           = 3
