aws_region         = "us-east-1"
project_name       = "agentic-devops"
environment        = "dev"
vpc_cidr           = "10.0.0.0/16"
availability_zones = ["us-east-1a", "us-east-1b"]
public_subnets     = ["10.0.1.0/24", "10.0.2.0/24"]
cluster_version    = "1.29"
node_instance_type = "t3.micro"
node_desired       = 1
node_min           = 1
node_max           = 2
